# Generated by Django 4.0.3 on 2022-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('contributeur', 'CONTRIBUTOR'), ('auteur', 'AUTHOR')], max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('FAIBLE', 'LOW'), ('MOYENNE', 'MEDIUM'), ('ÉLEVÉE', 'HIGH')], max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('À faire', 'TO_DO'), ('En cours', 'IN_PROGRESS'), ('Terminé', 'COMPLETED')], max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('AMÉLIORATION', 'IMPROVEMENT'), ('TÂCHE', 'TASK')], max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('back-end', 'BACKEND'), ('front-end', 'FRONTEND'), ('iOS', 'IOS'), ('Android', 'ANDROID')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(fields=('user_id', 'project_id'), name='unique_user_project'),
        ),
    ]
