# Generated by Django 4.0.5 on 2022-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0004_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('contributor', 'CONTRIBUTOR'), ('author', 'AUTHOR')], max_length=15),
        ),
    ]
