# Generated by Django 4.0.5 on 2022-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0005_alter_contributor_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='type',
        ),
    ]
